use_frameworks!

platform :ios, '10.0'

target 'ChooseOptionDropDownView_Example' do
  pod 'ChooseOptionDropDownView', :path => '../'

  target 'ChooseOptionDropDownView_Tests' do
    inherit! :search_paths

    
  end
end


post_install do |installer|
    print "Setting the default SWIFT_VERSION to 5.0\n"
   
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      end
    end
end
